#!/bin/bash

PROJECT="$(cat project/name.txt)"
OPTIONS="""
build - Build ${PROJECT}
clean - Remove old build of ${PROJECT}
"""

clear
echo "${PROJECT} buildsystem"

if [[ $1 == "build" ]]; then 
	echo "Build"
	mkdir -p build && cd build
	CC=clang CXX=clang++ cmake .. -Wno-dev -DCMAKE_BUILD_TYPE=Release -DJNI_USE_JNIVM=ON -DJNIVM_ENABLE_TRACE=ON
	make -j12
	cd ..
	echo "Built"
elif [[ $1 == "clean" ]]; then
	echo "Clean"
	rm -r build
else
	echo "${OPTIONS}"
fi
