#!/bin/bash

clear
echo "$(cat project/name.txt) buildsystem"

if [[ $1 == "build" ]]; then 
	echo "Build"
	mkdir -p build && cd build
	CC=clang CXX=clang++ cmake .. -Wno-dev -DCMAKE_BUILD_TYPE=Release -DJNI_USE_JNIVM=ON 
	make -j$(getconf _NPROCESSORS_ONLN)
	cd ..
	echo "Built"
elif [[ $1 == "clean" ]]; then
	echo "Clean"
	rm -r build
else
	echo "No valid option found"
fi
